### ISSUE TITLE
thanks for your code!

### ISSUE THREAD

**Issue by FunnyRainn** [wkim97/FSR#2]
thanks!~
1.but i want to know why my GPU just run with no more than 10% used?
2.is there any way to improve this as it is too slow?
maybe the Q above is too basic as i am a beginner ...
be grateful and look forward to your Answer!~

**Comment by wkim97** [comment]
Hi, thank you for your interest in our work!
Seems weird, because the code fully utilizes the GPU in our environment:
![image](https://github.com/wkim97/FSR/assets/48055164/8b0c00c9-6254-4e3d-8b92-9967a78a2ee0)

Can you share the CUDA and PyTorch versions in which you are running the code?
My environment is as follows:
1 RTX 3090 GPU
CUDA: 11.7
torch: 1.12.1

With this, training a single epoch on the CIFAR-10 dataset should take only a couple minutes.
