### ISSUE TITLE
Clarifications about VGG16 classification head

### ISSUE THREAD

**Issue by tgoncalv** [wkim97/FSR#7]
Hello, thank your nice work ! 
I was looking at your code and I noticed that your version of VGG16 uses a different architecture for the classification head compared to the original one. Is there any particular reasons that I have missed in your paper ? 

your code:
```your_code
        self.classifier = nn.Sequential(
            nn.Linear(512 * 1 * 1, 512),
            nn.ReLU(True),
            nn.Linear(512, 512),
            nn.ReLU(True),
            nn.Linear(512, num_classes)
        )
```

original code:
```original_architecture
        self.classifier = nn.Sequential(
            nn.Linear(512 * 7 * 7, 4096),
            nn.ReLU(True),
            nn.Dropout(p=dropout),
            nn.Linear(4096, 4096),
            nn.ReLU(True),
            nn.Dropout(p=dropout),
            nn.Linear(4096, num_classes),
        )
```

Thank you in advance !

**Comment by wkim97** [comment]
Hi tgoncalv,

Thank you for your interest in our work!
The main reason is due to the size of the input image. On CIFAR10 images of size 32 x 32, the VGG network will extract features of size 512 x 1 x 1. The original code assumes an input image of size 224 x 224, on which the VGG network will extract features of size 512 x 7 x 7.

You can also refer to these repositories that design VGG networks for CIFAR-10 images in a similar manner:
https://github.com/kuangliu/pytorch-cifar/tree/master/models
https://github.com/bymavis/CAS_ICLR2021

**Comment by tgoncalv** [comment]
Thank you for your quick answer and the references !
